core/urls.py
from django.urls import path, include
from django.views import generic
from .views import auth

# setup url configuration to serve media asset
from django.conf import settings

urlpatterns = [
    path('', generic.TemplateView.as_view(template_name='index.html'), name='index'),
    path('rentals/', include('rentals.urls', namespace='rentals')),
    path('register', auth.signup, name='register'),
    path('logout', auth.signout, name='logout'),
    path('login', auth.signin, name='login'),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

rentals/urls.py
from django.urls import path
from . import views

app_name = 'rentals'
urlpatterns = [
    path('find-student/', views.htmx_find_student, name='find_student'),
    path('rentage-price/', views.htmx_rentage_price, name='validate'),
    path('book-search/', views.htmx_book_search, name='search'),
    path('extend-rent/<int:id>/', views.extend_rent, name='extend_rent'),
    path('students/', views.students, name='students'),
    path('books/', views.books, name='books'),
    path('rent/', views.rent, name='rent'),
    path('', views.rentals, name='index'),
]

rentals/models.py
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.utils import timezone
from django.db import models

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    name = models.CharField(max_length=30, blank=True)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.name

    def is_admin(self):
        return self.is_staff
    

class Book(models.Model):
    total_pages = models.IntegerField(blank=False, null=False)
    cover_i = models.CharField(blank=False, null=False, max_length=225)
    title = models.CharField(blank=False, null=False, max_length=225)
    author = models.CharField(blank=False, null=False, max_length=225)


    def __str__(self) -> str:
        return f"{self.title} by {self.author} ({self.total_pages})"
    

class Student(models.Model):
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=30, blank=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self) -> str:
        return self.name
    

class Rental(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='rentals')
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='rentals')
    start_date = models.DateTimeField(blank=False, null=False, auto_now_add=True)
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    end_date = models.DateField(blank=False, null=False)

    def __str__(self) -> str:
        return f"{self.user} rented {self.book} from {self.start_date} to {self.end_date}"
    
    @property
    def is_returned(self) -> bool:
        return timezone.now().date() > self.end_date

rentals/forms.py
from django import forms



class NewRentalForm(forms.Form):
    student = forms.EmailField(required=True)
    book_name = forms.CharField(required=True)
    return_date = forms.DateField(required=True)


class NewStudentForm(forms.Form):
    name = forms.CharField(required=True)
    email = forms.EmailField(required=True)


class RentExtensionForm(forms.Form):
    date = forms.DateField(required=True)

rentals/views.py
from django.http import HttpRequest, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.shortcuts import render
from django.contrib import messages
from django.db import transaction
from django.utils import timezone
from .utils import compute_price
from django.urls import reverse
from . import models, forms
import requests



@login_required(redirect_field_name='redirect', login_url='/login')
def rentals(request:HttpRequest):
    return render(
        request, 
        'rentals.html', 
        context={
            'rentals': models.Rental.objects.all(), 
            'active': 'rentals'
        }
    )


@login_required(redirect_field_name='redirect', login_url='/login')
def students(request:HttpRequest):
    if request.method == "GET":
        return render(
            request, 
            'students.html', 
            context={
                'students': models.Student.objects.all().order_by('-created_at'), 
                'active': 'students'
            }
        )
    
    form = forms.NewStudentForm(request.POST)
    if not form.is_valid():
        return render(
            request,
            'students.html',
            context={
                'students': models.Student.objects.all().order_by('-created_at'),
                'active': 'students',
                'form': form
            }
        )
    
    try:
        models.Student.objects.create(
            name=form.cleaned_data['name'],
            email=form.cleaned_data['email']
        )
    except IntegrityError:
        messages.add_message(request, messages.ERROR, 'Student with the given email already exists')
        return HttpResponseRedirect(reverse('rentals:students'))

    messages.add_message(request, messages.SUCCESS, "New student added successfully")
    return HttpResponseRedirect(reverse('rentals:students'))


@login_required(redirect_field_name='redirect', login_url='/login')
def books(request:HttpRequest):
    return render(
        request, 'books.html', 
        context={
            'books': models.Book.objects.all(), 
            'active': 'books'
        }
    )


@login_required(redirect_field_name='redirect', login_url='/login')
def extend_rent(request:HttpRequest, id:int):
    """
    Processes request to extend book rentage return date.

    Returns HttpResponseRedirect

    Path Param:

    : id [int] -> Rental unique identifier
    """
    try:
        rental:models.Rental = models.Rental.objects.get(id=id)
    except models.Rental.DoesNotExist:
        messages.add_message(request, messages.ERROR, 'No rental found with the given id')
        return HttpResponseRedirect(reverse('rentals:index'))
    
    if rental.is_returned:
        messages.add_message(request, messages.ERROR, 'The book has already been returned')
        return HttpResponseRedirect(reverse('rentals:index'))
    
    form = forms.RentExtensionForm(request.POST)
    if not form.is_valid():
        return render(request, 'rentals.html', {'form': form})
    
    if form.cleaned_data['date'] < rental.end_date:
        messages.add_message(request, messages.ERROR, 'Extension date must be after the current return date')
        return HttpResponseRedirect(reverse('rentals:index'))
    
    rental.end_date = form.cleaned_data['date']
    rental.save()

    messages.add_message(request, messages.SUCCESS, 'Rental extended successfully')
    return HttpResponseRedirect(reverse('rentals:index'))
    

@login_required(redirect_field_name='redirect', login_url='/login')
def rent(request:HttpRequest):
    """
    Processes book rentage request. This allows a student to rent
    a book for a specified number of days. 

    Returns a HttpResponseRedirect 

    Query Params:
    
    : book_name [str]: Actual book name to be rented (this should be the title from open library)

    : student [str]: Student's email address - this should be a valid email address in the database

    : return date [date str]: A valid date string signifying the date the rentage is to last for.
    """
    form = forms.NewRentalForm(request.POST)

    if not form.is_valid():
        return render(request, 'rentage_cost.html', {'form': form})
    
    student = form.cleaned_data['student']
    book_name = form.cleaned_data['book_name']
    return_date = form.cleaned_data['return_date']

    try:
        student = models.Student.objects.get(email=student)
    except models.Student.DoesNotExist:
        messages.add_message(request, messages.ERROR, f'No student found for the given email : {student}')
        return HttpResponseRedirect(reverse('rentals:index'))
    
    is_book_from_db = False
    # attempt to retrieve book from the database with the given name. 
    # If the book is not found, attempt to retrieve from openlibrary.
    try:
        book:models.Book = models.Book.objects.get(title=book_name)
        title = book.title
        author_name = book.author
        pages = book.total_pages
        is_book_from_db = True
    except models.Book.DoesNotExist:
        try:
            response = requests.get(f"https://openlibrary.org/search.json?title={book_name}")
            data = response.json()['docs'][0]
            title = data['title']
            author_name = data['author_name'][0]
            pages = data['number_of_pages_median']
        except Exception as e:
            messages.add_message(
                request, 
                messages.ERROR, 
                f'Unable to retrieve book with the given title: {book_name}'
            )
            return HttpResponseRedirect(reverse('rentals:index'))

    try:
        price = compute_price(return_date, pages)
    except ValueError:
        return render(request, 'rentage_cost.html', {'error': 'Return date cannot be a past date'})


    # create a transaction to create a book and create rentage for the book
    try:
        with transaction.atomic():
            if not is_book_from_db:
                book = models.Book.objects.create(
                    title=title,
                    total_pages=pages,
                    author=author_name,
                )

            models.Rental.objects.create(
                book=book, 
                cost=price,
                student=student, 
                end_date=return_date, 
            )
    except Exception as e:
        messages.add_message(
            request,
            messages.ERROR,
            f'Unable to create book with the given title: {book_name}'
        )
        return HttpResponseRedirect(reverse('rentals:index'))

    return HttpResponseRedirect(reverse('rentals:index'))


def htmx_book_search(request:HttpRequest):
    """
    Processes request that searches for book using it's title from 
    openlibrary.

    The processed request returns an HTMLResponse containing the
    search result

    Query Params:

    : book [str]: The book title which is to be searched for
    """
    try:
        book:models.Book = models.Book.objects.filter(title__icontains=request.GET.get('book')).first()
        title = book.title
        author_name = book.author
        pages = book.total_pages
    except (models.Book.DoesNotExist, AttributeError):
        try:
            response = requests.get(f"https://openlibrary.org/search.json?title={request.GET.get('book')}")
            data = response.json()['docs'][0]
            title = data['title']
            author_name = data['author_name'][0]
            pages = data['number_of_pages_median']
        except:
            author_name = None
            pages = None
            title = None

    return render(request, 'search.html', {'author_name': author_name, 'pages': pages, 'title':title})


def htmx_find_student(request:HttpRequest):
    page = request.GET.get('page', 'rentals')
    
    if page == 'students':
        student = models.Student.objects.filter(email__iexact=request.GET.get('email')).first()
        return render(request, 'find_student.html', context={
            "student_name": "email taken" if student else ""
        })

    student = models.Student.objects.filter(email__startswith=request.GET.get('student')).first()
    return render(request, 'find_student.html', context={
        "student_name": student.name if student else "no match found"
    })


def htmx_rentage_price(request:HttpRequest):
    """
    Processes request that calculates the price of a rentage.

    The processed request returns an HTMLResponse containing the
    calculated price

    Query Params:

    : return_date [date str]: A valid date string signifying the date the rentage is to last for.

    : num_pages [int]: The number of pages in the book to be rented
    """
    page = request.GET.get('page', None)
    if page and page == 'rent_extension':
        date = timezone.datetime.strptime(request.GET.get('date'), '%Y-%m-%d').date()
        try:
            rent_id = int(request.GET.get('rent_id'))
            rental = models.Rental.objects.get(id=rent_id)
        except models.Rental.DoesNotExist:
            return render(request, 'rentage_cost.html', {'error': "Couldn't compute"})
        
        if date < rental.end_date:
            return render(request, 'rentage_cost.html', {'error': "Date < Rental return date"})
        
        if date.month == rental.end_date.month:
            return render(request, 'rentage_cost.html', {'price': 0})
        
        try:
            price = compute_price(date, rental.book.total_pages)
        except ValueError:
            return render(request, 'rentage_cost.html', {'error': 'Return date cannot be a past date'})
        
        return render(request, 'rentage_cost.html', {'error': None, 'price': price})
    
    else:

        return_date = request.GET.get('return_date')
        num_pages = request.GET.get('book_pages')
        if not return_date or not num_pages:
            return render(request, 'rentage_cost.html', {'error': "Pricing failed. Ensure all fields are filled"})

templates/find_student.html
<p class="text-xs text-gray-700">{{student_name}}</p>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book Rental | One Stop Shop For Book Renting</title>
    {% include 'includes/headers.html' %}
</head>
<body class="bg-gray-900">
    <section class="mx-auto w-10/12">
        <h1 class="text-4xl font-bold text-purple-400 mb-8 titan">Bokr</h1>
        <div class="md:flex justify-between place-items-center">
            <div class="mb-8 md:mb-0 text-white">
                <p class="text-3xl">Revolutionizing Traditional Library & Book Renting</p>
                <div class="mt-4">
                    <a href="{% url 'rentals:index' %}" class="rounded-sm bg-purple-800 p-1 h-10 w-28 flex place-items-center justify-center font-bold text-purple-200 hover:bg-purple-900 hover:text-purple-100">
                        Rent Book
                    </a>
                </div>

                <div class="mt-4">
                    <small class="text-gray-500 text-md">
                        2024 Award-Wining Online Book Store &nbsp; | &nbsp; 1st in IBC  &nbsp;| &nbsp; Over 5,000,000+ books rented
                    </small>
                </div>
            </div>
            <img src="{% static 'cover.png' %}" alt="" class="grow md:w-1/2">
        </div>
    </section>
    
    <section class="h-10 w-full bg-gray-700 my-2 p-1 flex place-items-center justify-center">
        <h2 class="text-gray-400 font-extrabold">Over 5,000,000+ Books Rented</h2>
    </section>

    <div id="app" class="text-white text-3xl"></div>
    <script>
        const { createApp } = Vue

        createApp({
            data() {
                return {
                    message: 'Hello Vue!'
                }
            }
        }).mount('#app')
    </script>
</body>
</html>

templates/rentage_cost.html
{% if error %}
<small>{{error}}</small>
{% else %}
<small class="text-center text-gray-500 font-extrabold">
    Rentage Cost ${{price}} <sub>(monthly)</sub>
</small>
{% endif %}

templates/search.html
{% if author_name and pages %}
<p class="text-xs text-gray-700">Written by {{author_name}} ({{pages}}<sub>p</sub>)</p>
<input type="hidden" name="book_name" value="{{ title }}">
<input type="hidden" name="bookpages" id="id_bookpages" value="{{pages}}">
{% else %}
<p class="text-xs text-red-700">Book not found. Ensure a valid book name is provided</p>
{% endif %}

templates/students.html
{% extends 'structures/dashboard.html' %}
{% load static %}
  
{% block dataarea %}
  <div id="modalBackdrop" class="fixed inset-0 z-50 bg-black opacity-75 hidden"></div>

  <div id="newStudentModal" class="fixed inset-0 flex items-center justify-center z-50 overflow-y-auto hidden">
    <div class="w-10/12 md:w-6/12 rounded-md min-h-[250px] bg-white p-8">
      <h3 class="text-2xl font-bold text-center">Add New Student</h3>

      <form method="post" action="{% url 'rentals:students' %}" class="my-8">
        {% csrf_token %}
        <label for="id_name">Student Name</label>
        <input type="text" placeholder="Enter Name" name="name" required id="id_name"
          class="border h-10 border-gray-400 w-full p-1 rounded-sm outline-none bookInputField">


        <div class="block place-items-center gap-4 mt-4">
          <div class="mb-4 md:mb-0 w-full">
            <div class="flex justify-between place-items-center">
              <label for="id_book">Student Email</label>
              <div id="htmx-find-student-target"></div>
            </div>

            <input type="email" id="id_email" required name="email" placeholder="Enter Email"
              hx-trigger="keyup changed delay:500ms" hx-target="#htmx-find-student-target"
              hx-get="{% url 'rentals:find_student' %}?page=students"
              class="h-10 border border-gray-400 w-full p-1 rounded-sm outline-none">
          </div>
        </div>


        <div class="flex flex-col justify-center place-items-center mt-8">
          <button type="submit"
            class="relative inline-flex items-center outline-none justify-center p-0.5 mb-2 me-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-600 to-blue-500 group-hover:from-purple-600 group-hover:to-blue-500 hover:text-white focus:outline-none">
            <span class="relative outline-none px-5 py-2.5 transition-all ease-in duration-75 bg-white rounded-md group-hover:bg-opacity-0">
              Add Student
            </span>
          </button>
          <p class="text-xs text-red-600 font-thin leading-8 closeModal cursor-pointer" data-modal="newStudentModal">Close</p>
        </div>
      </form>
    </div>
  </div>

  <div class="p-2 md:p-14 container grow">
    {% if messages %}
    {% for message in messages %}
    <div class="text-sm text-center font-bold text-red-500 mb-8">{{message}}</div>
    {% endfor %}
    {% endif %}

    {% if form.errors %}
      {% for field in form %}
           {% for error in field.errors %}
            <small class="text-sm text-red-500 font-bold"> {{field.label}}: {{ error|escape }} </small>
           {% endfor %}
      {% endfor %}
    {% endif %}
    

    <div class="">
      <div class="flex flex-row justify-between place-items-center mb-12">
        <h1 class="text-right text-2xl font-bold">Students</h1>

        <button
          class="relative inline-flex items-center outline-none justify-center p-0.5 mb-2 me-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-600 to-blue-500 group-hover:from-purple-600 group-hover:to-blue-500 hover:text-white focus:outline-none">
          <span id="openNewStudenModal" data-modal="newStudentModal"
            class="relative outline-none px-5 py-2.5 transition-all ease-in duration-75 bg-white rounded-md group-hover:bg-opacity-0">
            New Student
          </span>
        </button>
      </div>


    </div>

    <div class="relative block overflow-x-scroll shadow-md">
      <table class="w-full text-sm rtl:text-right text-gray-500">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:text-gray-400">
          <tr>
            <th scope="col" class="px-6 py-3">
              Name
            </th>
            <th scope="col" class="px-6 py-3">
              Email
            </th>
            <th scope="col" class="px-6 py-3">
              Current Rentage
            </th>
          </tr>
        </thead>
        <tbody>
          {% for student in students %}
          <tr class="bg-white text-center border-b hover:bg-gray-100 cursor-pointer">
            <th scope="row" class="px-6 py-4 font-medium whitespace-nowrap">
              {{student.name}}
            </th>
            <td class="px-6 py-4">
              {{student.email}}
            </td>
            <td class="px-6 py-4">
              {{student.rentals.count}}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

  </div>
{% endblock dataarea %}

{% block script %}
  <script>

    // Get modal elements
    const openNewStudenModal = document.getElementById('openNewStudenModal');
    const closeModalBtn = document.querySelectorAll('.closeModal');
    const modalBackdrop = document.getElementById('modalBackdrop');



    // Function to open modal
    function openModal(target) {
      const modal = document.getElementById(target);
      modal.classList.remove('hidden');
      modalBackdrop.classList.remove('hidden');
      document.body.classList.add('modal-open');
    }

    // Function to close modal
    function closeModal(target, removeBackdrop = true) {
      const modal = document.getElementById(target);
      modal.classList.add('hidden');
      if (removeBackdrop) {
        modalBackdrop.classList.add('hidden');
        document.body.classList.remove('modal-open');
      }
    }


    openNewStudenModal.addEventListener('click', (event) => {
      const targetModal = event.target.dataset['modal']
      openModal(targetModal)
    });

    // openModalBtn.forEach( btn => {
    //   btn.addEventListener('click', (event) => {
    //     const targetModal = event.target.dataset['modal']
    //     openModal(targetModal)
    //   });
    // })

    closeModalBtn.forEach(btn => {
      btn.addEventListener('click', (event) => {
        const targetModal = event.target.dataset['modal']
        closeModal(targetModal)
      });
    })

  </script>
  <script src="{% static 'htmx.min.js' %}" defer></script>
{% endblock script %}